name: build-and-push-ubuntu-22-04

on:
  #   schedule:
  #     - cron: "20 11 * * *"
  push:
    branches: [main]
    paths:
      - "Dockerfile.ubuntu2204"
      
jobs:
  build-multi-arch-image:
    name: Build multi-arch Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          file: ./Dockerfile.ubuntu2004
          tags: ghcr.io/${{ github.repository }}:ubuntu2204
          platforms: linux/amd64, linux/arm64
